MAX_ITERATIONS: int = 40
MAX_AGENTS_PER_TURN: int = 12
MAX_LIST_FILE_PER_ORCHESTRATOR_TURN: int = 1
TITLE_FORCE_BY_TURN: int = 8

SUBAGENT_MAX_TURNS: int = 40
SUBAGENT_TIMEOUT_SEC: float = 1080.0  # 18 minutes
MAX_OUTPUT_TOKENS_RECOVERY_LIMIT: int = 3

MAX_CONCURRENT_TOOLS: int = 5
AGENT_OUTPUT_COMPACT_THRESHOLD: int = 4000
SPAWN_SUMMARY_MAX: int = 2000
ACTIVITY_RESULT_MAX: int = 2000
ACTIVITY_COUNT_MAX: int = 200

LOCK_TTL_SEC: int = 90
LOCK_REFRESH_INTERVAL_SEC: float = 20.0

GATE_TTL_SEC: int = 1200
POLL_INTERVAL_MS: int = 300
MAX_CONSECUTIVE_ERRORS: int = 10
TOOL_REJECTED_RESULT: str = "[Tool rejected by user]"
